-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 16:41:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Talleres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Talleres
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Talleres` DEFAULT CHARACTER SET utf8 ;
USE `Talleres` ;

-- -----------------------------------------------------
-- Table `Talleres`.`registrar_taller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Talleres`.`registrar_taller` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NombreTallerista` VARCHAR(100) NOT NULL,
  `NombreTaller` VARCHAR(80) NOT NULL,
  `Calendario` VARCHAR(60) NOT NULL,
  `Capacidad` INT NOT NULL,
  `Turno` ENUM("Matutino", "Vespertino") NOT NULL,
  `Tipo` VARCHAR(50) NOT NULL,
  `Dia` ENUM("Martes", "Jueves") NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Talleres`.`mostrar_talleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Talleres`.`mostrar_talleres` (
  `idTalleres` INT NOT NULL AUTO_INCREMENT,
  `NombreTallerista` VARCHAR(100) NOT NULL,
  `NombreTaller` VARCHAR(80) NOT NULL,
  `Calendario` VARCHAR(60) NOT NULL,
  `Capacidad` INT NOT NULL,
  `Turno` ENUM("Matutino", "Vespertino") NOT NULL,
  `Tipo` VARCHAR(50) NOT NULL,
  `Dia` ENUM("Martes", "Jueves") NOT NULL,
  `Registrados` INT NOT NULL,
  `Lugares_Faltantes` INT NOT NULL,
  PRIMARY KEY (`idTalleres`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Talleres`.`usuarios_talleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Talleres`.`usuarios_talleres` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Carrera` VARCHAR(60) NOT NULL,
  `NombreTallerista` VARCHAR(100) NOT NULL,
  `NombreTaller` VARCHAR(80) NOT NULL,
   `Ingreso` VARCHAR(100) NOT NULL,
   `Turno` ENUM("Matutino", "Vespertino") NOT NULL,
      `Dia` ENUM("Martes", "Jueves") NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Talleres`.`calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Talleres`.`calendario` (
  `idCalendario` INT NOT NULL AUTO_INCREMENT,
  `FechaInicial` DATE NOT NULL,
  `FechaFinal` DATE NOT NULL,
  PRIMARY KEY (`idCalendario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
